<a href="https://colab.research.google.com/github/leecy05/Tutorial3/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr_2x2 = np.array([[1, 2],
                    [3, 4]])
print("2x2 array:\n", arr_2x2)

2x2 array:
 [[1 2]
 [3 4]]


In [4]:
rand_3x4 = np.random.rand(3, 4)  # values between 0 and 1
print("Random 3x4 array:\n", rand_3x4)

Random 3x4 array:
 [[0.95938097 0.48737741 0.59925988 0.81461119]
 [0.06032954 0.96245725 0.908979   0.75184721]
 [0.03686724 0.33457475 0.38662528 0.66225596]]


In [5]:
ones_arr = np.ones((2, 3))
zeros_arr = np.zeros((2, 3))

print("Array of ones:\n", ones_arr)
print("Array of zeroes:\n", zeros_arr)

Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
rand_6x3 = np.random.rand(6, 3)
print("Original 6x3 array:\n", rand_6x3)

transpose_arr = rand_6x3.T
print("Transposed array (3x6):\n", transpose_arr)

Original 6x3 array:
 [[0.28920629 0.17259444 0.11729219]
 [0.16698547 0.39674371 0.71047781]
 [0.32213875 0.97710986 0.5111148 ]
 [0.85532507 0.59809376 0.29137661]
 [0.91243169 0.54575773 0.06276898]
 [0.36066364 0.05183537 0.46013505]]
Transposed array (3x6):
 [[0.28920629 0.16698547 0.32213875 0.85532507 0.91243169 0.36066364]
 [0.17259444 0.39674371 0.97710986 0.59809376 0.54575773 0.05183537]
 [0.11729219 0.71047781 0.5111148  0.29137661 0.06276898 0.46013505]]


In [7]:
A = np.random.rand(2, 3)
B = np.random.rand(3, 4)

dot_product = np.dot(A, B)
print("Matrix A (2x3):\n", A)
print("Matrix B (3x4):\n", B)
print("Dot product (2x4):\n", dot_product)

Matrix A (2x3):
 [[0.52849694 0.46158628 0.58963624]
 [0.78293474 0.32592228 0.4088096 ]]
Matrix B (3x4):
 [[0.66551047 0.96010235 0.5634078  0.87308856]
 [0.63678196 0.46841291 0.55918072 0.07113566]
 [0.91254295 0.25389473 0.14936067 0.19248082]]
Dot product (2x4):
 [[1.18371845 0.87332966 0.6439379  0.60775354]
 [1.10164901 1.00815829 0.68442106 0.78544407]]
